# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Unity-iPhone' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GPUImage'
  pod 'YYModel'
  pod 'YYCategories'
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'TOCropViewController'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'DGActivityIndicatorView'
  pod 'ReactiveObjC'
  pod 'FTPopOverMenu'
  pod 'AFMInfoBanner'
  # Pods for Unity-iPhone

  target 'Unity-iPhone Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
